# Generated by Django 3.2.4 on 2021-08-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_glimpses_glimpsesimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
